#!/bin/sh
# Joins the twelve script files into one, for pasting into Apps Script as `Code`.
# The roster is deliberately NOT included: paste private/Roster.gs separately
# as a script file named `Roster`.
set -e
cd "$(dirname "$0")/.."
OUT=dist/YMU-Mentoring-AllInOne.gs
mkdir -p dist

{
  echo "/**"
  echo " * YMU Mentoring — all twelve script files joined into one."
  echo " * GENERATED by tools/build-bundle.sh. Edit apps-script/*.gs, not this."
  echo " *"
  echo " * Paste into Apps Script as a SCRIPT file named  Code."
  echo " * The ambassador roster is NOT here — paste private/Roster.gs"
  echo " * separately as a SCRIPT file named  Roster."
  echo " */"
  echo
  for f in Config Setup Geo Closures Cycles Availability \
           Scheduling Matching Panel Templates Feedback MenteeApp Reminders WebApp; do
    echo ""
    echo "/* ================================================================"
    echo "   $f.gs"
    echo "   ================================================================ */"
    echo ""
    cat "apps-script/$f.gs"
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
